# This workflow will build Quotes project

name: Quotes

on:
  push:
    branches:
    - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Restore dependencies (install Nuget packages)
      run: dotnet restore

    - name: Build and publish the app
      run: |
        dotnet build --no-restore
        dotnet publish -c Release -o ./publish        

    - name: Upload app artifacts to Github
      uses: actions/upload-artifact@v4
      with:
        name: app-artifacts
        path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Download app artifacts
      uses: actions/download-artifact@v4
      with:
        name: app-artifacts
        path: ./publish

    - name: Set up SSH key and config
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        cat >> ~/.ssh/config <<EOF
        Host bastion
          HostName ${{ secrets.BASTION_IP }}
          User azureuser
          IdentityFile ~/.ssh/id_rsa
          StrictHostKeyChecking no

        Host appvm
          HostName ${{ secrets.APPVM_IP }}
          User azureuser
          IdentityFile ~/.ssh/id_rsa
          StrictHostKeyChecking no
          ProxyJump bastion
        EOF

        chmod 600 ~/.ssh/config

    - name: Deploy to App VM via Bastion
      run: |
        scp -r ./publish/* appvm:/tmp/myapp-release/
        ssh appvm 'sudo systemctl stop myapp.service && sudo rm -rf /opt/myapp/* && sudo cp -r /tmp/myapp-release/* /opt/myapp/ && sudo chown -R azureuser:azureuser /opt/myapp && sudo systemctl start myapp.service && rm -rf /tmp/myapp-release'

    - name: Verify deployment
      run: |
        ssh appvm 'systemctl is-active myapp.service'
